services:

  postgres:
      image: 'postgres:latest'
      ports:
        - "5432:5432"
      deploy:
        mode: replicated
        replicas: 1
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: users
      volumes:
        - postgres:/var/lib/postgresql/data/

volumes:
  postgres: